name: Automatic prerelease generation at PR opening
run-name: Automatic prerelease generation at PR opening - PR${{ github.event.number }}
on:
  pull_request:
    types:
      - opened
permissions:
  contents: write
jobs:
  trigger:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/github-script@v6
        env:
          head_ref: ${{ github.head_ref }}
          head_sha: ${{ github.event.pull_request.head.sha }}
        with:
          retries: 3
          script: |
            const lastPrereleaseWorkflow = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "release.yml",
              branch: process.env.head_ref,
              head_sha: process.env.head_sha,
              per_page: 1
            });
            
            console.log(JSON.stringify(lastPrereleaseWorkflow));

            if (lastPrereleaseWorkflow && lastPrereleaseWorkflow.total_count === 1){
              const run_id = lastPrereleaseWorkflow.actions.workflow_runs[0].id;
              await github.rest.actions.reRunWorkflow({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run_id
              });
            }


