name: Automatic prerelease generation at PR opening
run-name: Automatic prerelease generation at PR opening - PR${{ github.event.number }}
on:
  pull_request:
    types:
      - opened
permissions:
  contents: write
jobs:
  trigger:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Empty commit generation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "chore(bot): Automatic prerelease generation at PR opening"
          git push
